name = "safhetk"
main = "server.js"
type = "webpack"
account_id = "YOUR_ACCOUNT_ID" # استبدل هذا برقم حساب Cloudflare الخاص بك
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-04-10"

[site]
bucket = "."
entry-point = "./"

[build]
command = ""

[env.production]
name = "safhetk-prod"

[build.upload]
format = "service-worker" 