name = "safhetk"
main = "server.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[build]
command = "npm install"

[env.production]
name = "safhetk-prod"

[build.upload]
format = "service-worker" 